spring:
  application:
    name: autom-back-end
  datasource:
    url: jdbc:mysql://localhost:3306/atoms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: Asia/Shanghai

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: info
